export const enum HeaderName {
    CONTENT_TYPE = 'Content-Type',
    CONTENT_LENGTH = 'Content-Length',
    ACCEPT = 'Accept',
    CACHE_CONTROL = 'Cache-Control',
    CONNECTION = 'Connection',
    AUTHORIZATION = 'Authorization',
    SET_COOKIE = 'Set-Cookie',
    ORIGIN = 'Origin',
    VARY = 'Vary',
    ACCESS_CONTROL_REQUEST_METHOD = 'Access-Control-Request-Method',
    ACCESS_CONTROL_REQUEST_HEADERS = 'Access-Control-Request-Headers',
    ACCESS_CONTROL_ALLOW_ORIGIN = 'Access-Control-Allow-Origin',
    ACCESS_CONTROL_ALLOW_METHODS = 'Access-Control-Allow-Methods',
    ACCESS_CONTROL_ALLOW_HEADERS = 'Access-Control-Allow-Headers',
    ACCESS_CONTROL_ALLOW_CREDENTIALS = 'Access-Control-Allow-Credentials',
    ACCESS_CONTROL_EXPOSE_HEADERS = 'Access-Control-Expose-Headers',
    ACCESS_CONTROL_MAX_AGE = 'Access-Control-Max-Age',
}
