import type {AnyAttributes, CommonProps} from '../jsx-types'
import type {AnchorElement} from './AnchorElement'
import type {ScriptElementAttributes} from './ScriptElement'
import type {ButtonAttributes} from './ButtonElement'
import type {StyleHTMLAttributes} from './StyleAttributes'


export type IntrinsicElements = {
    /**
     * The <a> HTML element (or anchor element), with its href attribute, creates a hyperlink to web pages, files,
     * email addresses, locations in the same page, or anything else a URL can address.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
     */
    a: AnchorElement & CommonProps,
    abbr: AnyAttributes,
    acronym: AnyAttributes,
    address: AnyAttributes,
    area: AnyAttributes,
    article: AnyAttributes,
    aside: AnyAttributes,
    audio: AnyAttributes,
    b: AnyAttributes,
    base: AnyAttributes,
    bdi: AnyAttributes,
    bdo: AnyAttributes,
    big: AnyAttributes,
    blockquote: AnyAttributes,
    body: AnyAttributes,
    br: AnyAttributes,
    button: ButtonAttributes  & CommonProps,
    canvas: AnyAttributes,
    caption: AnyAttributes,
    center: AnyAttributes,
    cite: AnyAttributes,
    code: AnyAttributes,
    col: AnyAttributes,
    colgroup: AnyAttributes,
    content: AnyAttributes,
    data: AnyAttributes,
    datalist: AnyAttributes,
    dd: AnyAttributes,
    del: AnyAttributes,
    details: AnyAttributes,
    dfn: AnyAttributes,
    dialog: AnyAttributes,
    dir: AnyAttributes,
    div: AnyAttributes,
    dl: AnyAttributes,
    dt: AnyAttributes,
    em: AnyAttributes,
    embed: AnyAttributes,
    fieldset: AnyAttributes,
    figcaption: AnyAttributes,
    figure: AnyAttributes,
    font: AnyAttributes,
    footer: AnyAttributes,
    form: AnyAttributes,
    frame: AnyAttributes,
    frameset: AnyAttributes,
    h1: AnyAttributes,
    h2: AnyAttributes,
    h3: AnyAttributes,
    h4: AnyAttributes,
    h5: AnyAttributes,
    h6: AnyAttributes,
    head: AnyAttributes,
    header: AnyAttributes,
    hgroup: AnyAttributes,
    hr: AnyAttributes,
    html: AnyAttributes,
    i: AnyAttributes,
    iframe: AnyAttributes,
    image: AnyAttributes,
    img: AnyAttributes,
    /**
     * The `<input>` HTML element is used to create interactive controls for web-based forms in order to accept data
     * from the user; a wide variety of types of input data and control widgets are available, depending on the device
     * and user agent. The `<input>` element is one of the most powerful and complex in all of HTML due to the sheer
     * number of combinations of input types and attributes.
     */
    input: AnyAttributes,
    ins: AnyAttributes,
    kbd: AnyAttributes,
    keygen: AnyAttributes,
    label: AnyAttributes,
    legend: AnyAttributes,
    li: AnyAttributes,
    link: AnyAttributes,
    main: AnyAttributes,
    map: AnyAttributes,
    mark: AnyAttributes,
    marquee: AnyAttributes,
    menu: AnyAttributes,
    menuitem: AnyAttributes,
    meta: AnyAttributes,
    meter: AnyAttributes,
    nav: AnyAttributes,
    nobr: AnyAttributes,
    noembed: AnyAttributes,
    noframes: AnyAttributes,
    noscript: AnyAttributes,
    object: AnyAttributes,
    ol: AnyAttributes,
    optgroup: AnyAttributes,
    option: AnyAttributes,
    output: AnyAttributes,
    p: AnyAttributes,
    param: AnyAttributes,
    picture: AnyAttributes,
    plaintext: AnyAttributes,
    portal: AnyAttributes,
    pre: AnyAttributes,
    progress: AnyAttributes,
    q: AnyAttributes,
    rb: AnyAttributes,
    rp: AnyAttributes,
    rt: AnyAttributes,
    rtc: AnyAttributes,
    ruby: AnyAttributes,
    s: AnyAttributes,
    samp: AnyAttributes,
    script: ScriptElementAttributes,
    search: AnyAttributes,
    section: AnyAttributes,
    select: AnyAttributes,
    shadow: AnyAttributes,
    slot: AnyAttributes,
    small: AnyAttributes,
    source: AnyAttributes,
    span: AnyAttributes,
    strike: AnyAttributes,
    strong: AnyAttributes,
    style: StyleHTMLAttributes,
    sub: AnyAttributes,
    summary: AnyAttributes,
    sup: AnyAttributes,
    table: AnyAttributes,
    tbody: AnyAttributes,
    td: AnyAttributes,
    template: AnyAttributes,
    textarea: AnyAttributes,
    tfoot: AnyAttributes,
    th: AnyAttributes,
    thead: AnyAttributes,
    time: AnyAttributes,
    title: AnyAttributes,
    tr: AnyAttributes,
    track: AnyAttributes,
    tt: AnyAttributes,
    u: AnyAttributes,
    ul: AnyAttributes,
    var: AnyAttributes,
    video: AnyAttributes,
    wbr: AnyAttributes,
    xmp: AnyAttributes,
}
