import type {AnyAttributes, CommonProps} from '../jsx-types'
import type {AnchorElement} from './AnchorElement'
import type {ScriptElementAttributes} from './ScriptElement'
import type {ButtonAttributes} from './ButtonElement'
import type {StyleHTMLAttributes} from './StyleAttributes'


export type IntrinsicElements = {
    /**
     * The <a> HTML element (or anchor element), with its href attribute, creates a hyperlink to web pages, files,
     * email addresses, locations in the same page, or anything else a URL can address.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
     */
    a: AnchorElement & CommonProps<HTMLAnchorElement>,
    abbr: AnyAttributes,
    acronym: AnyAttributes,
    address: AnyAttributes,
    area: AnyAttributes<HTMLAreaElement>,
    article: AnyAttributes,
    aside: AnyAttributes,
    audio: AnyAttributes<HTMLAudioElement>,
    b: AnyAttributes,
    base: AnyAttributes<HTMLBaseElement>,
    bdi: AnyAttributes,
    bdo: AnyAttributes,
    big: AnyAttributes,
    blockquote: AnyAttributes<HTMLQuoteElement>,
    body: AnyAttributes<HTMLBodyElement>,
    br: AnyAttributes<HTMLBRElement>,
    button: ButtonAttributes  & CommonProps<HTMLButtonElement>,
    canvas: AnyAttributes<HTMLCanvasElement>,
    caption: AnyAttributes<HTMLTableCaptionElement>,
    center: AnyAttributes,
    cite: AnyAttributes,
    code: AnyAttributes,
    col: AnyAttributes<HTMLTableColElement>,
    colgroup: AnyAttributes<HTMLTableColElement>,
    content: AnyAttributes,
    data: AnyAttributes<HTMLDataElement>,
    datalist: AnyAttributes<HTMLDataListElement>,
    dd: AnyAttributes,
    del: AnyAttributes<HTMLModElement>,
    details: AnyAttributes<HTMLDetailsElement>,
    dfn: AnyAttributes,
    dialog: AnyAttributes<HTMLDialogElement>,
    dir: AnyAttributes,
    div: AnyAttributes<HTMLDivElement>,
    dl: AnyAttributes<HTMLDListElement>,
    dt: AnyAttributes,
    em: AnyAttributes,
    embed: AnyAttributes<HTMLEmbedElement>,
    fieldset: AnyAttributes<HTMLFieldSetElement>,
    figcaption: AnyAttributes,
    figure: AnyAttributes,
    font: AnyAttributes,
    footer: AnyAttributes,
    form: AnyAttributes<HTMLFormElement>,
    frame: AnyAttributes,
    frameset: AnyAttributes,
    h1: AnyAttributes<HTMLHeadingElement>,
    h2: AnyAttributes<HTMLHeadingElement>,
    h3: AnyAttributes<HTMLHeadingElement>,
    h4: AnyAttributes<HTMLHeadingElement>,
    h5: AnyAttributes<HTMLHeadingElement>,
    h6: AnyAttributes<HTMLHeadingElement>,
    head: AnyAttributes<HTMLHeadElement>,
    header: AnyAttributes,
    hgroup: AnyAttributes,
    hr: AnyAttributes<HTMLHRElement>,
    html: AnyAttributes<HTMLHtmlElement>,
    i: AnyAttributes,
    iframe: AnyAttributes<HTMLIFrameElement>,
    image: AnyAttributes,
    img: AnyAttributes<HTMLImageElement>,
    /**
     * The `<input>` HTML element is used to create interactive controls for web-based forms in order to accept data
     * from the user; a wide variety of types of input data and control widgets are available, depending on the device
     * and user agent. The `<input>` element is one of the most powerful and complex in all of HTML due to the sheer
     * number of combinations of input types and attributes.
     */
    input: AnyAttributes<HTMLInputElement>,
    ins: AnyAttributes<HTMLModElement>,
    kbd: AnyAttributes,
    keygen: AnyAttributes,
    label: AnyAttributes<HTMLLabelElement>,
    legend: AnyAttributes<HTMLLegendElement>,
    li: AnyAttributes<HTMLLIElement>,
    link: AnyAttributes<HTMLLinkElement>,
    main: AnyAttributes,
    map: AnyAttributes<HTMLMapElement>,
    mark: AnyAttributes,
    marquee: AnyAttributes,
    menu: AnyAttributes<HTMLMenuElement>,
    menuitem: AnyAttributes,
    meta: AnyAttributes<HTMLMetaElement>,
    meter: AnyAttributes<HTMLMeterElement>,
    nav: AnyAttributes,
    nobr: AnyAttributes,
    noembed: AnyAttributes,
    noframes: AnyAttributes,
    noscript: AnyAttributes,
    object: AnyAttributes<HTMLObjectElement>,
    ol: AnyAttributes<HTMLOListElement>,
    optgroup: AnyAttributes<HTMLOptGroupElement>,
    option: AnyAttributes<HTMLOptionElement>,
    output: AnyAttributes<HTMLOutputElement>,
    p: AnyAttributes<HTMLParagraphElement>,
    param: AnyAttributes<HTMLParamElement>,
    picture: AnyAttributes<HTMLPictureElement>,
    plaintext: AnyAttributes,
    portal: AnyAttributes,
    pre: AnyAttributes<HTMLPreElement>,
    progress: AnyAttributes<HTMLProgressElement>,
    q: AnyAttributes<HTMLQuoteElement>,
    rb: AnyAttributes,
    rp: AnyAttributes,
    rt: AnyAttributes,
    rtc: AnyAttributes,
    ruby: AnyAttributes,
    s: AnyAttributes,
    samp: AnyAttributes,
    script: ScriptElementAttributes,
    search: AnyAttributes,
    section: AnyAttributes,
    select: AnyAttributes<HTMLSelectElement>,
    shadow: AnyAttributes,
    slot: AnyAttributes<HTMLSlotElement>,
    small: AnyAttributes,
    source: AnyAttributes<HTMLSourceElement>,
    span: AnyAttributes<HTMLSpanElement>,
    strike: AnyAttributes,
    strong: AnyAttributes,
    style: StyleHTMLAttributes,
    sub: AnyAttributes,
    summary: AnyAttributes,
    sup: AnyAttributes,
    table: AnyAttributes<HTMLTableElement>,
    tbody: AnyAttributes<HTMLTableSectionElement>,
    td: AnyAttributes<HTMLTableCellElement>,
    template: AnyAttributes<HTMLTemplateElement>,
    textarea: AnyAttributes<HTMLTextAreaElement>,
    tfoot: AnyAttributes<HTMLTableSectionElement>,
    th: AnyAttributes<HTMLTableCellElement>,
    thead: AnyAttributes<HTMLTableSectionElement>,
    time: AnyAttributes<HTMLTimeElement>,
    title: AnyAttributes<HTMLTitleElement>,
    tr: AnyAttributes<HTMLTableRowElement>,
    track: AnyAttributes<HTMLTrackElement>,
    tt: AnyAttributes,
    u: AnyAttributes,
    ul: AnyAttributes<HTMLUListElement>,
    var: AnyAttributes,
    video: AnyAttributes<HTMLVideoElement>,
    wbr: AnyAttributes,
    xmp: AnyAttributes,
}
