#!/usr/bin/env -S bun test
import { describe, expect, it } from 'bun:test'
import { HttpMethod } from '@mpen/http-helpers'
import { Router } from '../router'
import { openapi } from '../handlers/openapi'
import type { OpenApiDocument } from '../handlers/openapi'
import { zodRoute } from '../routes/zod'
import { z } from 'zod'

type JsonSchemaObject = {
    type?: string
    properties: Record<string, JsonSchemaObject>
}

type OperationWithSchemas = {
    requestBody: {
        content: Record<string, { schema: JsonSchemaObject }>
    }
    responses: Record<string, { content: Record<string, { schema: JsonSchemaObject }> }>
    parameters: unknown[]
}

describe('openapi', () => {
    it('consumes route schemas generated by zodRoute', async () => {
        const router = new Router()
        router.add(
            zodRoute({
                path: '/users/:id',
                method: HttpMethod.POST,
                schema: {
                    request: {
                        path: z.object({ id: z.string() }),
                        query: z.object({ include: z.string() }),
                        body: z.object({ name: z.string() }),
                    },
                    response: {
                        body: {
                            200: z.object({ ok: z.boolean() }),
                        },
                    },
                },
                validateResponse: false,
                handler: () => new Response('ok'),
            }),
        )

        router.add({
            path: '/swagger.json',
            method: HttpMethod.GET,
            handler: openapi({
                info: { title: 'Example API', version: '1.0.0' },
            }),
        })

        const response = await router.fetch(new Request('https://example.com/swagger.json'))
        const document = (await response.json()) as OpenApiDocument
        const operation = document.paths['/users/{id}'].post as OperationWithSchemas

        expect(operation.requestBody.content['application/json'].schema.type).toBe('object')
        expect(operation.requestBody.content['application/json'].schema.properties.name.type).toBe(
            'string',
        )
        expect(
            operation.responses['200'].content['application/json'].schema.properties.ok.type,
        ).toBe('boolean')
        expect(operation.parameters).toEqual(
            expect.arrayContaining([
                expect.objectContaining({ name: 'id', in: 'path' }),
                expect.objectContaining({ name: 'include', in: 'query' }),
            ]),
        )
    })
})
